# Color settings for Terminal and iterm2
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
alias ls='ls -FGh'

# set rm to ask for permission
alias rm="rm -i"

# added by Anaconda2 2.5.0 installer
export PATH="/Users/shaneflynn/anaconda/bin:$PATH"

# Set git bath
if [ -f ~/.git-completion.bash ]; then
    source ~/.git-completion.bash
fi

# Open xcode from terminal
alias xcode="open -a Xcode"

# Open textedit from terminal
alias textedit='open -a TextEdit'
